name: 'Setup AWS CLI'
description: 'Setup your workflow with AWS CLI'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
inputs:
  version:
    description: 'AWS CLI version to use.'
    required: true
    default: '1.32.71'
  python_version:
    description: Python Version (defaults to 3.12)
    required: true
    default: '3.12'
  aws-region:
    description: AWS Region, e.g. us-east-2
    required: false
  aws-access-key-id:
    description: >- 
      AWS Access Key ID. Provide this key if you want to assume a role 
      using access keys rather than a web identity token.
    required: false
  aws-secret-access-key:
    description: AWS Secret Access Key. Required if aws-access-key-id is provided.
    required: false

runs:
    using: 'composite'
    steps:
      - name: Check Runner OS
        if: ${{ runner.os != 'Linux' }}
        shell: bash
        run: |
          echo "::error title=⛔ error hint::Support Linux Only"
          exit 1
      - name: setup python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install AWS CLI
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
        run: pip install --quiet --no-cache-dir awscli==${VERSION}
      - name: Setup AWS CLI
        shell: bash
        run: echo "::info title=ℹ️ info hint::Automatic configure coming soon"
