name: aws-cli

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  VERSION: 1.32.71

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: AWS CLI Action
        uses: ./
        with:
          version: "$VERSION"

      - name: Check for AWS CLI version
        run:
            aws --version | grep -q "$VERSION"
